// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHX59HWjG-xjWSClEC0wUvfcUkEkEYvZE',
    appId: '1:1049578695285:web:43a11e52887887afcb663c',
    messagingSenderId: '1049578695285',
    projectId: 'what-bytes-task-app',
    authDomain: 'what-bytes-task-app.firebaseapp.com',
    storageBucket: 'what-bytes-task-app.firebasestorage.app',
    measurementId: 'G-67L821W9WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpPrpH7Zv-IGWeUtRuJpSzn9dg2HWzoEE',
    appId: '1:1049578695285:android:b512f5ed4470fe08cb663c',
    messagingSenderId: '1049578695285',
    projectId: 'what-bytes-task-app',
    storageBucket: 'what-bytes-task-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XcNsHimWuIgVBwT0ODuTGUn_4et7BC4',
    appId: '1:1049578695285:ios:972e4b9e1749c047cb663c',
    messagingSenderId: '1049578695285',
    projectId: 'what-bytes-task-app',
    storageBucket: 'what-bytes-task-app.firebasestorage.app',
    iosBundleId: 'com.example.whatBytesTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4XcNsHimWuIgVBwT0ODuTGUn_4et7BC4',
    appId: '1:1049578695285:ios:972e4b9e1749c047cb663c',
    messagingSenderId: '1049578695285',
    projectId: 'what-bytes-task-app',
    storageBucket: 'what-bytes-task-app.firebasestorage.app',
    iosBundleId: 'com.example.whatBytesTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHX59HWjG-xjWSClEC0wUvfcUkEkEYvZE',
    appId: '1:1049578695285:web:3e3e1c18e5ece257cb663c',
    messagingSenderId: '1049578695285',
    projectId: 'what-bytes-task-app',
    authDomain: 'what-bytes-task-app.firebaseapp.com',
    storageBucket: 'what-bytes-task-app.firebasestorage.app',
    measurementId: 'G-8RHEMY9R09',
  );
}
